Repository whamcloud/Vagrantfiles, pull requests merged in 2019-05, with the labels that each got.

#38 Update b2_12 repo links
  iml-sandbox/Vagrantfile
Labels: tech debt

#40 Ensure crossover network is deterministic
  iml-sandbox/Vagrantfile
Labels: bug

#41 Add IML 5.0 provisioner
  iml-sandbox/Vagrantfile
Labels: enhancement

#42 Disable devel repo after installing vbox fencing
  iml-sandbox/Vagrantfile
Labels: bug

#43 Fix 5.0 repo and lustre client provisioning script
  iml-sandbox/Vagrantfile
Labels: bug

#44 Monitored ZFS updates
  iml-sandbox/Vagrantfile
Labels: bug

#26 - Add provisioning script to configure vm's for local networking with docker containers
  iml-sandbox/Vagrantfile
Labels: enhancement

#46 Default to manager-for-lustre-devel for local installs
  iml-sandbox/Vagrantfile
Labels: enhancement
